[package]
name = "keyboard_gen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
atomic_float = "0.1.0"
colored = "2.0.4"
getrandom = { version = "0.2.10", features = ["js"] }
rand = "0.8.5"
rayon = "1.7.0"
