[package]
name = "keyboard_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_float = "0.1.0"
colored = "2.0.4"
rand = "0.8.5"
rayon = "1.7.0"
